# Q1 請造一個10*5的矩陣空間，並按由下而上 、由左至右、按順序0~49填滿他

In [9]:
import numpy as np

a=np.arange(0,50,1)
b=a.reshape(10,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [16]:
for i in range(10):
    a=np.arange(i,50,10)
    print(a)
    
print('********************')

b=np.arange(50)
c=b.reshape(5,10)
print(c.T)

[ 0 10 20 30 40]
[ 1 11 21 31 41]
[ 2 12 22 32 42]
[ 3 13 23 33 43]
[ 4 14 24 34 44]
[ 5 15 25 35 45]
[ 6 16 26 36 46]
[ 7 17 27 37 47]
[ 8 18 28 38 48]
[ 9 19 29 39 49]
********************
[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


# Q2 九九乘法表 for & while

In [46]:
for i in range(1,10):
    for j in range(1,10):
        print('%dx%d=%d \t' %(j,i, i*j),end='')
    print('')

1x1=1 	2x1=2 	3x1=3 	4x1=4 	5x1=5 	6x1=6 	7x1=7 	8x1=8 	9x1=9 	
1x2=2 	2x2=4 	3x2=6 	4x2=8 	5x2=10 	6x2=12 	7x2=14 	8x2=16 	9x2=18 	
1x3=3 	2x3=6 	3x3=9 	4x3=12 	5x3=15 	6x3=18 	7x3=21 	8x3=24 	9x3=27 	
1x4=4 	2x4=8 	3x4=12 	4x4=16 	5x4=20 	6x4=24 	7x4=28 	8x4=32 	9x4=36 	
1x5=5 	2x5=10 	3x5=15 	4x5=20 	5x5=25 	6x5=30 	7x5=35 	8x5=40 	9x5=45 	
1x6=6 	2x6=12 	3x6=18 	4x6=24 	5x6=30 	6x6=36 	7x6=42 	8x6=48 	9x6=54 	
1x7=7 	2x7=14 	3x7=21 	4x7=28 	5x7=35 	6x7=42 	7x7=49 	8x7=56 	9x7=63 	
1x8=8 	2x8=16 	3x8=24 	4x8=32 	5x8=40 	6x8=48 	7x8=56 	8x8=64 	9x8=72 	
1x9=9 	2x9=18 	3x9=27 	4x9=36 	5x9=45 	6x9=54 	7x9=63 	8x9=72 	9x9=81 	


In [53]:
i=1
while i<10:
    j=1
    while j<10:
        print('%dx%d=%d \t' % (j,i,i*j), end='')
        j+=1
    i+=1
    print()

1x1=1 	2x1=2 	3x1=3 	4x1=4 	5x1=5 	6x1=6 	7x1=7 	8x1=8 	9x1=9 	
1x2=2 	2x2=4 	3x2=6 	4x2=8 	5x2=10 	6x2=12 	7x2=14 	8x2=16 	9x2=18 	
1x3=3 	2x3=6 	3x3=9 	4x3=12 	5x3=15 	6x3=18 	7x3=21 	8x3=24 	9x3=27 	
1x4=4 	2x4=8 	3x4=12 	4x4=16 	5x4=20 	6x4=24 	7x4=28 	8x4=32 	9x4=36 	
1x5=5 	2x5=10 	3x5=15 	4x5=20 	5x5=25 	6x5=30 	7x5=35 	8x5=40 	9x5=45 	
1x6=6 	2x6=12 	3x6=18 	4x6=24 	5x6=30 	6x6=36 	7x6=42 	8x6=48 	9x6=54 	
1x7=7 	2x7=14 	3x7=21 	4x7=28 	5x7=35 	6x7=42 	7x7=49 	8x7=56 	9x7=63 	
1x8=8 	2x8=16 	3x8=24 	4x8=32 	5x8=40 	6x8=48 	7x8=56 	8x8=64 	9x8=72 	
1x9=9 	2x9=18 	3x9=27 	4x9=36 	5x9=45 	6x9=54 	7x9=63 	8x9=72 	9x9=81 	


In [56]:
a = "hello world"
b = "***********"
print(a.rjust(50))
print(b.rjust(50))

                                       hello world
                                       ***********


# 畫菱形

In [13]:
a=' '
b='*'
for i in range(1,8):
     x=(7-i)*a
     y=(2*i-1)*b
     print(x+y)
for j in range(6,0,-1):
     x=(2*j-1)*b
     y= (7-j)*a
     print(y+x)

      *
     ***
    *****
   *******
  *********
 ***********
*************
 ***********
  *********
   *******
    *****
     ***
      *


In [12]:
s='*'
print('how many layers u want')
rows=int(input())

for i in range(1,rows*2+1,2):
    print((s*i).center(50))
for j in range((rows-1)*2-1,0,-2):
    print((s*j).center(50))

how many layers u want
5
                        *                         
                       ***                        
                      *****                       
                     *******                      
                   ***********                    
                    *********                     
                     *******                      
                      *****                       
                       ***                        
                        *                         


In [6]:
rows=int(input('layers'))
col=1

for i in range(0rows+1):
    print(('*'*col).center(70))
    if rows/2 < i+1:
        space=-2
    else:
        space=2
    col+=space
    print(i)

layers12
                                  *                                   
0
                                 ***                                  
1
                                *****                                 
2
                               *******                                
3
                              *********                               
4
                             ***********                              
5
                            *************                             
6
                             ***********                              
7
                              *********                               
8
                               *******                                
9
                                *****                                 
10
                                 ***                                  
11
