在list中新增內容，append vs extend

append:將所賦予之添加物整包插入原陣列中

extend:將所賦予之陣列逐項插入原陣列中

In [6]:
#利用append增加內容
# a=[1,2,3,4,5,6]
# print('原陣列:', a)
# a.append(14)
# print('調整陣列:',a)

# a.append([1,2,3,2,1])
# print('調整陣列:', a)

#利用extend增加內容
a=[1,2,3,4,5,6]
print('原陣列:', a)
a.extend([14,3,2,1])
print('調整陣列:',a)

原陣列: [1, 2, 3, 4, 5, 6]
調整陣列: [1, 2, 3, 4, 5, 6, 14, 3, 2, 1]


# 在特定座標插入物件:

In [10]:
a=[1,2,3,4,5,6]
#插入數字:
a.insert(2,100)
print('調整陣列:',a)
#插入矩陣:
a.insert(2,[100,199])
print('調整矩陣:',a)

調整陣列: [1, 2, 100, 3, 4, 5, 6]
調整矩陣: [1, 2, [100, 199], 100, 3, 4, 5, 6]


# remove & del 

In [37]:
a=[1,2,3,4,5,6]
a.remove(2) # 針對該list中的元素移除
print('remove後的a矩陣:' , a)
b=[1,2,3,4,5,6]
del b[2] #依照list中的order去刪除
print('del後的b矩陣:' , b)

remove後的a矩陣: [1, 3, 4, 5, 6]
del後的b矩陣: [1, 2, 4, 5, 6]


# range & numpy

In [25]:
a= range(10,50,5)
for i in a:
    print(i)
print('************************')

import numpy as np
a=np.arange(30,10,-5)
print(a)

10
15
20
25
30
35
40
45
************************
[30 25 20 15]


 # 二維陣列

In [36]:
a=np.arange(20)
print('原陣列a:', a)
a=a.reshape(4,5) #變成4乘5矩陣
print('reshape後的a:',a)

b=np.arange(10,70,10)
b=b.reshape(2,-1) #可以只丟一邊，-1讓電腦去算
print('reshape後的b',b)

原陣列a: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
reshape後的a: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
reshape後的b [[10 20 30]
 [40 50 60]]


In [53]:
# 大小維4*10，全部為1的矩陣
import numpy as np
a=np.ones((4,10),dtype=int)
print(a,)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


# 邏輯分析

In [52]:
print(1 in range(10))
print(1 in np.arange(10))

True
True
