In [9]:
a = [1, 2, 3]
b = [2, 5, 8]
aa = ['123', 'sdfsd']

c = {'1':a, '2':b, '3':aa, 1:[789, 321], 1.21:[123,654]}

print(c)

print(c['2'])

print(c[1])
print(c[1.21])

{'1': [1, 2, 3], '2': [2, 5, 8], '3': ['123', 'sdfsd'], 1: [789, 321], 1.21: [123, 654]}
[2, 5, 8]
[789, 321]
[123, 654]


# 	Q1. 請問如何產生一個大小維 4*10, 全部都為 1 的矩陣

In [38]:
import numpy as np

a = np.ones((4, 10, 5, 6, 4, 1))

print(a.shape)

(4, 10, 5, 6, 4, 1)


In [26]:
i = np.ones(40)

# print(i)


a = np.reshape(i, (4, 10))

c = i.reshape((4, 10))

b = np.arange(10)
b

print(c)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [38]:
a = np.arange(2., 42)
b = np.arange(1., 41)

c = a-b

print(c)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [47]:
a = np.tile(1, (4, 10))

print(a)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [37]:
a = np.eye(4)

print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# a : 2*5
# b : 5*2

# c = a*b : 2*2

In [1]:
a = 1
b = 1.

print(type(a))
print(type(b))

print(a + b)

c = a+b+0.8
print(int(c))


<class 'int'>
<class 'float'>
2.0
2


# Q2. 請造一個 10 x 5 的矩陣空間，並按由上而下、從左至右、按順序0~49填滿他

In [61]:
a = np.arange(50)
a = np.reshape(a, (5, 10))
# a = np.transpose(a)
print(a.T)
print(a)

[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [20]:
b = []
for i in range(10):
    a = list(range(i, 50, 10))
    b.append(a)
    
# b
# a
b = np.array(b)
print(b)

[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]
 [ 4 14 24 34 44]
 [ 5 15 25 35 45]
 [ 6 16 26 36 46]
 [ 7 17 27 37 47]
 [ 8 18 28 38 48]
 [ 9 19 29 39 49]]


In [16]:



for i in range(10):
    a = np.arange(i, 50, 10)
    
    print(a)
#    i = i + 100

[ 0 10 20 30 40]
[ 1 11 21 31 41]
[ 2 12 22 32 42]
[ 3 13 23 33 43]
[ 4 14 24 34 44]
[ 5 15 25 35 45]
[ 6 16 26 36 46]
[ 7 17 27 37 47]
[ 8 18 28 38 48]
[ 9 19 29 39 49]


In [21]:
i = 0

while(i < 10):
    j = 0
    
    while(j < 5):
        
        print('%d, ' %((i+10*j)), end = '')
        
        j += 1
    
    i += 1
    print()

0, 10, 20, 30, 40, 
1, 11, 21, 31, 41, 
2, 12, 22, 32, 42, 
3, 13, 23, 33, 43, 
4, 14, 24, 34, 44, 
5, 15, 25, 35, 45, 
6, 16, 26, 36, 46, 
7, 17, 27, 37, 47, 
8, 18, 28, 38, 48, 
9, 19, 29, 39, 49, 


In [29]:
print('a + b = 3')

print('%s + %s = %1.9f' %('a', 'b', 413.1354648))

a + b = 3
a + b = 413.135464800


In [45]:
# 特殊寫法!!!
a = np.arange(50)

mat = np.zeros((10, 5))

i_count = 0
for i_c in range(5):
    for i_r in range(10):
        
        mat[i_r][i_c] = a[i_count]
        
        i_count += 1
print(mat)

[[ 0. 10. 20. 30. 40.]
 [ 1. 11. 21. 31. 41.]
 [ 2. 12. 22. 32. 42.]
 [ 3. 13. 23. 33. 43.]
 [ 4. 14. 24. 34. 44.]
 [ 5. 15. 25. 35. 45.]
 [ 6. 16. 26. 36. 46.]
 [ 7. 17. 27. 37. 47.]
 [ 8. 18. 28. 38. 48.]
 [ 9. 19. 29. 39. 49.]]


In [96]:
a = np.arange(50)

row, col = 10, 5 
mat = np.zeros((row, col))

for i in a:
    
    i_r = int(i % row)
    i_c = int(i / row)
    
#     print('i_r, i_c: (%1.2f, %1.2f)' %(i_r, i_c))
    
    mat[i_r][i_c] = i
print(mat)

[[ 0. 10. 20. 30. 40.]
 [ 1. 11. 21. 31. 41.]
 [ 2. 12. 22. 32. 42.]
 [ 3. 13. 23. 33. 43.]
 [ 4. 14. 24. 34. 44.]
 [ 5. 15. 25. 35. 45.]
 [ 6. 16. 26. 36. 46.]
 [ 7. 17. 27. 37. 47.]
 [ 8. 18. 28. 38. 48.]
 [ 9. 19. 29. 39. 49.]]


# Q4. 以 while 迴圈做出一個九九乘法表

In [108]:
i = 1
while i < 10:
    j = 1
    while j < 10:
        
        print('%dx%d=%2d\t' %(j, i, j*i), end = '')
        
        j += 1
    
    i += 1
    print()

1x1= 1	2x1= 2	3x1= 3	4x1= 4	5x1= 5	6x1= 6	7x1= 7	8x1= 8	9x1= 9	
1x2= 2	2x2= 4	3x2= 6	4x2= 8	5x2=10	6x2=12	7x2=14	8x2=16	9x2=18	
1x3= 3	2x3= 6	3x3= 9	4x3=12	5x3=15	6x3=18	7x3=21	8x3=24	9x3=27	
1x4= 4	2x4= 8	3x4=12	4x4=16	5x4=20	6x4=24	7x4=28	8x4=32	9x4=36	
1x5= 5	2x5=10	3x5=15	4x5=20	5x5=25	6x5=30	7x5=35	8x5=40	9x5=45	
1x6= 6	2x6=12	3x6=18	4x6=24	5x6=30	6x6=36	7x6=42	8x6=48	9x6=54	
1x7= 7	2x7=14	3x7=21	4x7=28	5x7=35	6x7=42	7x7=49	8x7=56	9x7=63	
1x8= 8	2x8=16	3x8=24	4x8=32	5x8=40	6x8=48	7x8=56	8x8=64	9x8=72	
1x9= 9	2x9=18	3x9=27	4x9=36	5x9=45	6x9=54	7x9=63	8x9=72	9x9=81	


# Q6. 畫個菱形

In [55]:
row = 12
space = 2
cent = 50
i_count = 1

for i in range(row+1):
    
    print(('*' * i_count).center(cent))
    
    if i+1 > row/2:
        space = -2
    
    i_count += space



                        *                         
                       ***                        
                      *****                       
                     *******                      
                    *********                     
                   ***********                    
                  *************                   
                   ***********                    
                    *********                     
                     *******                      
                      *****                       
                       ***                        
                        *                         


# 用 1, 2, 3, 4 可以組合出的所有的三位數，每一個位元不重複

In [121]:

num = 5
i_count = 0
for x in range(1, num):
    for y in range(1, num):
        for z in range(1, num):
            
            if (x != y) and (y != z) and (z != x):
#                 print('%d %d %d' %(x, y, z))
                i_count += 1
print(i_count)

24


# 一個整數， 加上 100 及 268 後都是完全平方數，請問該數是多少

In [128]:
num = 10000

for i in range(num):
    
    val = i**2  # 確定為完全平方數
    
    val2 = val - 100 + 268
    
    val2_sqrt = np.sqrt(val2)
    
    if val2_sqrt == int(val2_sqrt):
        
        print(val-100)
    
#     print(val)

-99
21
261
1581


In [62]:
for i in range(-100,10000):
    x=i+100
    y=i+268
    if x**0.5==int(x**0.5) and y**0.5==int(y**0.5):
        print(i)

-99
21
261
1581


In [57]:
100**0.5

10.0

In [59]:
21+268

289